export default class AutogeneratedStorage {
  constructor(initial) {
    this.values = initial;
  }

  generate() {
    throw new Error("Not specified");
  }

  getValues() {
    return storage;
  }

  clean() {
    storage = {};
  }
}
